# Generated by Django 4.0.5 on 2022-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('D', 'Domingo'), ('S', 'Segunda'), ('T', 'Terça'), ('Q', 'Quarta'), ('Q', 'Quinta'), ('S', 'Sexta'), ('S', 'Sábado')], max_length=250)),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('funcao', models.CharField(choices=[('F', 'Folga'), ('P', 'Produção'), ('F', 'Finalização'), ('S', 'Slash'), ('Q', 'QA'), ('I', 'Inventário'), ('F', 'Fechamento'), ('A', 'Almoço'), ('J', 'Janta')], max_length=250)),
            ],
        ),
    ]
