# Generated by Django 4.0.5 on 2022-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='praca',
            field=models.CharField(choices=[('C', 'Combinados'), ('E', 'Entradas'), ('R', 'Rolls'), ('B', 'Brisas')], default='None', max_length=250),
        ),
    ]
