# Generated by Django 4.0.5 on 2022-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0005_alter_escala_dia_alter_escala_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='praca',
            field=models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250),
        ),
    ]
