# Generated by Django 4.0.5 on 2022-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0007_rename_funcao_escala_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('atividade', models.CharField(choices=[('Fol', 'Folga'), ('Pro', 'Produção'), ('Fin', 'Finalização'), ('Sla', 'Slash'), ('QA', 'QA'), ('Inv', 'Inventário'), ('Fec', 'Fechamento'), ('Alm', 'Almoço'), ('Jan', 'Janta')], max_length=250)),
                ('praca', models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=250)),
                ('atividade', models.ManyToManyField(to='Escala.atividade')),
            ],
        ),
        migrations.DeleteModel(
            name='Escala',
        ),
    ]
