# Generated by Django 4.0.5 on 2022-06-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0008_atividade_funcionario_delete_escala'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Escala',
        ),
    ]
