# Generated by Django 4.0.5 on 2022-06-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0009_rename_funcionario_escala'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escala',
            new_name='Funcionario',
        ),
    ]
