# Generated by Django 4.0.5 on 2022-06-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0010_rename_escala_funcionario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Botafogo',
        ),
    ]
