# Generated by Django 4.0.5 on 2022-06-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0011_rename_funcionario_botafogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipanema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=250)),
                ('atividade', models.ManyToManyField(to='Escala.atividade')),
            ],
        ),
    ]
