# Generated by Django 4.0.5 on 2022-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0013_rename_botafogo_escalabotafogo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ipanema',
            new_name='EscalaFMALL',
        ),
        migrations.CreateModel(
            name='EscalaTijuca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=250)),
                ('atividade', models.ManyToManyField(to='Escala.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaRioSul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=250)),
                ('atividade', models.ManyToManyField(to='Escala.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaRDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=250)),
                ('atividade', models.ManyToManyField(to='Escala.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaIpanema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=250)),
                ('atividade', models.ManyToManyField(to='Escala.atividade')),
            ],
        ),
    ]
