# Generated by Django 4.0.5 on 2022-06-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0014_rename_ipanema_escalafmall_escalatijuca_escalariosul_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscalaFMALL',
            new_name='BotafogoEscala',
        ),
        migrations.RenameModel(
            old_name='EscalaTijuca',
            new_name='FMALLEscala',
        ),
        migrations.RenameModel(
            old_name='EscalaRDB',
            new_name='IpanemaEscala',
        ),
        migrations.RenameModel(
            old_name='EscalaRioSul',
            new_name='RDBEscala',
        ),
        migrations.RenameModel(
            old_name='EscalaIpanema',
            new_name='RioSulEscala',
        ),
        migrations.RenameModel(
            old_name='EscalaBotafogo',
            new_name='TijucaEscala',
        ),
    ]
