# Generated by Django 4.0.5 on 2022-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0015_rename_escalafmall_botafogoescala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMALLAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('atividade', models.CharField(choices=[('Fol', 'Folga'), ('Pro', 'Produção'), ('Fin', 'Finalização'), ('Sla', 'Slash'), ('QA', 'QA'), ('Inv', 'Inventário'), ('Fec', 'Fechamento'), ('Alm', 'Almoço'), ('Jan', 'Janta')], max_length=250)),
                ('praca', models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='IpanemaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('atividade', models.CharField(choices=[('Fol', 'Folga'), ('Pro', 'Produção'), ('Fin', 'Finalização'), ('Sla', 'Slash'), ('QA', 'QA'), ('Inv', 'Inventário'), ('Fec', 'Fechamento'), ('Alm', 'Almoço'), ('Jan', 'Janta')], max_length=250)),
                ('praca', models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RDBAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('atividade', models.CharField(choices=[('Fol', 'Folga'), ('Pro', 'Produção'), ('Fin', 'Finalização'), ('Sla', 'Slash'), ('QA', 'QA'), ('Inv', 'Inventário'), ('Fec', 'Fechamento'), ('Alm', 'Almoço'), ('Jan', 'Janta')], max_length=250)),
                ('praca', models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RioSulAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('atividade', models.CharField(choices=[('Fol', 'Folga'), ('Pro', 'Produção'), ('Fin', 'Finalização'), ('Sla', 'Slash'), ('QA', 'QA'), ('Inv', 'Inventário'), ('Fec', 'Fechamento'), ('Alm', 'Almoço'), ('Jan', 'Janta')], max_length=250)),
                ('praca', models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TijucaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('7', '7 Hrs'), ('8', '8 Hrs'), ('9', '9 Hrs'), ('10', '10 Hrs'), ('11', '11 Hrs'), ('12', '12 Hrs'), ('13', '13 Hrs'), ('14', '14 Hrs'), ('15', '15 Hrs'), ('16', '16 Hrs'), ('17', '17 Hrs'), ('18', '18 Hrs'), ('19', '19 Hrs'), ('20', '20 Hrs'), ('21', '21 Hrs'), ('22', '22 Hrs'), ('23', '23 Hrs'), ('00', '00 Hrs'), ('01', '01 Hrs')], max_length=250)),
                ('atividade', models.CharField(choices=[('Fol', 'Folga'), ('Pro', 'Produção'), ('Fin', 'Finalização'), ('Sla', 'Slash'), ('QA', 'QA'), ('Inv', 'Inventário'), ('Fec', 'Fechamento'), ('Alm', 'Almoço'), ('Jan', 'Janta')], max_length=250)),
                ('praca', models.CharField(choices=[('N', 'Nenhuma'), ('C', 'Combinados'), ('ENT', 'Entradas'), ('ES', 'Entradas Sushibar'), ('Rol', 'Rolls'), ('RQ', 'Rolls Quentes'), ('RF', 'Rolls Frios'), ('BDE', 'Brisas Duplas Entradas'), ('Fri', 'Fritadeira'), ('FOG', 'Fogão'), ('Sob', 'Sobremesas'), ('Sus', 'Sushi Brisas'), ('Lim', 'Limpeza'), ('Pro', 'Produção')], default='Nenhuma', max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Atividade',
            new_name='BotafogoAtividade',
        ),
        migrations.AlterField(
            model_name='fmallescala',
            name='atividade',
            field=models.ManyToManyField(to='Escala.fmallatividade'),
        ),
        migrations.AlterField(
            model_name='ipanemaescala',
            name='atividade',
            field=models.ManyToManyField(to='Escala.ipanemaatividade'),
        ),
        migrations.AlterField(
            model_name='rdbescala',
            name='atividade',
            field=models.ManyToManyField(to='Escala.rdbatividade'),
        ),
        migrations.AlterField(
            model_name='riosulescala',
            name='atividade',
            field=models.ManyToManyField(to='Escala.riosulatividade'),
        ),
        migrations.AlterField(
            model_name='tijucaescala',
            name='atividade',
            field=models.ManyToManyField(to='Escala.tijucaatividade'),
        ),
    ]
