# Generated by Django 4.0.5 on 2022-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escala', '0016_fmallatividade_ipanemaatividade_rdbatividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botafogoatividade',
            name='atividade',
            field=models.CharField(choices=[('Folga', 'Folga'), ('Produção', 'Produção'), ('Finalização', 'Finalização'), ('Slash', 'Slash'), ('QA', 'QA'), ('Inventário', 'Inventário'), ('Fechamento', 'Fechamento'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], max_length=250),
        ),
        migrations.AlterField(
            model_name='botafogoatividade',
            name='hora',
            field=models.CharField(choices=[('7hrs', '7 Hrs'), ('8hrs', '8 Hrs'), ('9hrs', '9 Hrs'), ('10hrs', '10 Hrs'), ('11hrs', '11 Hrs'), ('12hrs', '12 Hrs'), ('13hrs', '13 Hrs'), ('14hrs', '14 Hrs'), ('15hrs', '15 Hrs'), ('16hrs', '16 Hrs'), ('17hrs', '17 Hrs'), ('18hrs', '18 Hrs'), ('19hrs', '19 Hrs'), ('20hrs', '20 Hrs'), ('21hrs', '21 Hrs'), ('22hrs', '22 Hrs'), ('23hrs', '23 Hrs'), ('00hrs', '00 Hrs'), ('01hrs', '01 Hrs')], max_length=250),
        ),
        migrations.AlterField(
            model_name='botafogoatividade',
            name='praca',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Combinados', 'Combinados'), ('Entradas', 'Entradas'), ('Entradas Sushibar', 'Entradas Sushibar'), ('Rolls', 'Rolls'), ('Rolls Quentes', 'Rolls Quentes'), ('Rolls Frios', 'Rolls Frios'), ('Brisas Duplas Entradas', 'Brisas Duplas Entradas'), ('Fritadeira', 'Fritadeira'), ('Fogão', 'Fogão'), ('Sobremesas', 'Sobremesas'), ('Sushi Brisas', 'Sushi Brisas'), ('Limpeza', 'Limpeza'), ('Produção', 'Produção')], default='Nenhuma', max_length=250),
        ),
        migrations.AlterField(
            model_name='botafogoescala',
            name='dia',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=250),
        ),
        migrations.AlterField(
            model_name='fmallatividade',
            name='atividade',
            field=models.CharField(choices=[('Folga', 'Folga'), ('Produção', 'Produção'), ('Finalização', 'Finalização'), ('Slash', 'Slash'), ('QA', 'QA'), ('Inventário', 'Inventário'), ('Fechamento', 'Fechamento'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], max_length=250),
        ),
        migrations.AlterField(
            model_name='fmallatividade',
            name='hora',
            field=models.CharField(choices=[('7hrs', '7 Hrs'), ('8hrs', '8 Hrs'), ('9hrs', '9 Hrs'), ('10hrs', '10 Hrs'), ('11hrs', '11 Hrs'), ('12hrs', '12 Hrs'), ('13hrs', '13 Hrs'), ('14hrs', '14 Hrs'), ('15hrs', '15 Hrs'), ('16hrs', '16 Hrs'), ('17hrs', '17 Hrs'), ('18hrs', '18 Hrs'), ('19hrs', '19 Hrs'), ('20hrs', '20 Hrs'), ('21hrs', '21 Hrs'), ('22hrs', '22 Hrs'), ('23hrs', '23 Hrs'), ('00hrs', '00 Hrs'), ('01hrs', '01 Hrs')], max_length=250),
        ),
        migrations.AlterField(
            model_name='fmallatividade',
            name='praca',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Combinados', 'Combinados'), ('Entradas', 'Entradas'), ('Entradas Sushibar', 'Entradas Sushibar'), ('Rolls', 'Rolls'), ('Rolls Quentes', 'Rolls Quentes'), ('Rolls Frios', 'Rolls Frios'), ('Brisas Duplas Entradas', 'Brisas Duplas Entradas'), ('Fritadeira', 'Fritadeira'), ('Fogão', 'Fogão'), ('Sobremesas', 'Sobremesas'), ('Sushi Brisas', 'Sushi Brisas'), ('Limpeza', 'Limpeza'), ('Produção', 'Produção')], default='Nenhuma', max_length=250),
        ),
        migrations.AlterField(
            model_name='fmallescala',
            name='dia',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=250),
        ),
        migrations.AlterField(
            model_name='ipanemaatividade',
            name='atividade',
            field=models.CharField(choices=[('Folga', 'Folga'), ('Produção', 'Produção'), ('Finalização', 'Finalização'), ('Slash', 'Slash'), ('QA', 'QA'), ('Inventário', 'Inventário'), ('Fechamento', 'Fechamento'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], max_length=250),
        ),
        migrations.AlterField(
            model_name='ipanemaatividade',
            name='hora',
            field=models.CharField(choices=[('7hrs', '7 Hrs'), ('8hrs', '8 Hrs'), ('9hrs', '9 Hrs'), ('10hrs', '10 Hrs'), ('11hrs', '11 Hrs'), ('12hrs', '12 Hrs'), ('13hrs', '13 Hrs'), ('14hrs', '14 Hrs'), ('15hrs', '15 Hrs'), ('16hrs', '16 Hrs'), ('17hrs', '17 Hrs'), ('18hrs', '18 Hrs'), ('19hrs', '19 Hrs'), ('20hrs', '20 Hrs'), ('21hrs', '21 Hrs'), ('22hrs', '22 Hrs'), ('23hrs', '23 Hrs'), ('00hrs', '00 Hrs'), ('01hrs', '01 Hrs')], max_length=250),
        ),
        migrations.AlterField(
            model_name='ipanemaatividade',
            name='praca',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Combinados', 'Combinados'), ('Entradas', 'Entradas'), ('Entradas Sushibar', 'Entradas Sushibar'), ('Rolls', 'Rolls'), ('Rolls Quentes', 'Rolls Quentes'), ('Rolls Frios', 'Rolls Frios'), ('Brisas Duplas Entradas', 'Brisas Duplas Entradas'), ('Fritadeira', 'Fritadeira'), ('Fogão', 'Fogão'), ('Sobremesas', 'Sobremesas'), ('Sushi Brisas', 'Sushi Brisas'), ('Limpeza', 'Limpeza'), ('Produção', 'Produção')], default='Nenhuma', max_length=250),
        ),
        migrations.AlterField(
            model_name='ipanemaescala',
            name='dia',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=250),
        ),
        migrations.AlterField(
            model_name='rdbatividade',
            name='atividade',
            field=models.CharField(choices=[('Folga', 'Folga'), ('Produção', 'Produção'), ('Finalização', 'Finalização'), ('Slash', 'Slash'), ('QA', 'QA'), ('Inventário', 'Inventário'), ('Fechamento', 'Fechamento'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], max_length=250),
        ),
        migrations.AlterField(
            model_name='rdbatividade',
            name='hora',
            field=models.CharField(choices=[('7hrs', '7 Hrs'), ('8hrs', '8 Hrs'), ('9hrs', '9 Hrs'), ('10hrs', '10 Hrs'), ('11hrs', '11 Hrs'), ('12hrs', '12 Hrs'), ('13hrs', '13 Hrs'), ('14hrs', '14 Hrs'), ('15hrs', '15 Hrs'), ('16hrs', '16 Hrs'), ('17hrs', '17 Hrs'), ('18hrs', '18 Hrs'), ('19hrs', '19 Hrs'), ('20hrs', '20 Hrs'), ('21hrs', '21 Hrs'), ('22hrs', '22 Hrs'), ('23hrs', '23 Hrs'), ('00hrs', '00 Hrs'), ('01hrs', '01 Hrs')], max_length=250),
        ),
        migrations.AlterField(
            model_name='rdbatividade',
            name='praca',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Combinados', 'Combinados'), ('Entradas', 'Entradas'), ('Entradas Sushibar', 'Entradas Sushibar'), ('Rolls', 'Rolls'), ('Rolls Quentes', 'Rolls Quentes'), ('Rolls Frios', 'Rolls Frios'), ('Brisas Duplas Entradas', 'Brisas Duplas Entradas'), ('Fritadeira', 'Fritadeira'), ('Fogão', 'Fogão'), ('Sobremesas', 'Sobremesas'), ('Sushi Brisas', 'Sushi Brisas'), ('Limpeza', 'Limpeza'), ('Produção', 'Produção')], default='Nenhuma', max_length=250),
        ),
        migrations.AlterField(
            model_name='rdbescala',
            name='dia',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=250),
        ),
        migrations.AlterField(
            model_name='riosulatividade',
            name='atividade',
            field=models.CharField(choices=[('Folga', 'Folga'), ('Produção', 'Produção'), ('Finalização', 'Finalização'), ('Slash', 'Slash'), ('QA', 'QA'), ('Inventário', 'Inventário'), ('Fechamento', 'Fechamento'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], max_length=250),
        ),
        migrations.AlterField(
            model_name='riosulatividade',
            name='hora',
            field=models.CharField(choices=[('7hrs', '7 Hrs'), ('8hrs', '8 Hrs'), ('9hrs', '9 Hrs'), ('10hrs', '10 Hrs'), ('11hrs', '11 Hrs'), ('12hrs', '12 Hrs'), ('13hrs', '13 Hrs'), ('14hrs', '14 Hrs'), ('15hrs', '15 Hrs'), ('16hrs', '16 Hrs'), ('17hrs', '17 Hrs'), ('18hrs', '18 Hrs'), ('19hrs', '19 Hrs'), ('20hrs', '20 Hrs'), ('21hrs', '21 Hrs'), ('22hrs', '22 Hrs'), ('23hrs', '23 Hrs'), ('00hrs', '00 Hrs'), ('01hrs', '01 Hrs')], max_length=250),
        ),
        migrations.AlterField(
            model_name='riosulatividade',
            name='praca',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Combinados', 'Combinados'), ('Entradas', 'Entradas'), ('Entradas Sushibar', 'Entradas Sushibar'), ('Rolls', 'Rolls'), ('Rolls Quentes', 'Rolls Quentes'), ('Rolls Frios', 'Rolls Frios'), ('Brisas Duplas Entradas', 'Brisas Duplas Entradas'), ('Fritadeira', 'Fritadeira'), ('Fogão', 'Fogão'), ('Sobremesas', 'Sobremesas'), ('Sushi Brisas', 'Sushi Brisas'), ('Limpeza', 'Limpeza'), ('Produção', 'Produção')], default='Nenhuma', max_length=250),
        ),
        migrations.AlterField(
            model_name='riosulescala',
            name='dia',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tijucaatividade',
            name='atividade',
            field=models.CharField(choices=[('Folga', 'Folga'), ('Produção', 'Produção'), ('Finalização', 'Finalização'), ('Slash', 'Slash'), ('QA', 'QA'), ('Inventário', 'Inventário'), ('Fechamento', 'Fechamento'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tijucaatividade',
            name='hora',
            field=models.CharField(choices=[('7hrs', '7 Hrs'), ('8hrs', '8 Hrs'), ('9hrs', '9 Hrs'), ('10hrs', '10 Hrs'), ('11hrs', '11 Hrs'), ('12hrs', '12 Hrs'), ('13hrs', '13 Hrs'), ('14hrs', '14 Hrs'), ('15hrs', '15 Hrs'), ('16hrs', '16 Hrs'), ('17hrs', '17 Hrs'), ('18hrs', '18 Hrs'), ('19hrs', '19 Hrs'), ('20hrs', '20 Hrs'), ('21hrs', '21 Hrs'), ('22hrs', '22 Hrs'), ('23hrs', '23 Hrs'), ('00hrs', '00 Hrs'), ('01hrs', '01 Hrs')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tijucaatividade',
            name='praca',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Combinados', 'Combinados'), ('Entradas', 'Entradas'), ('Entradas Sushibar', 'Entradas Sushibar'), ('Rolls', 'Rolls'), ('Rolls Quentes', 'Rolls Quentes'), ('Rolls Frios', 'Rolls Frios'), ('Brisas Duplas Entradas', 'Brisas Duplas Entradas'), ('Fritadeira', 'Fritadeira'), ('Fogão', 'Fogão'), ('Sobremesas', 'Sobremesas'), ('Sushi Brisas', 'Sushi Brisas'), ('Limpeza', 'Limpeza'), ('Produção', 'Produção')], default='Nenhuma', max_length=250),
        ),
        migrations.AlterField(
            model_name='tijucaescala',
            name='dia',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=250),
        ),
    ]
